target("wsi")
    set_kind("static")
    set_target_layout("common/wsi")
    add_files("wsi/*.cpp")
    add_includedirs(".", {public = true})
    add_packages("glm", "function2", {public = true})
    add_packages("glfw", "imgui", {public = false})
    add_deps("etna")
target_end()

target("scene")
    set_kind("static")
    set_target_layout("common/scene")
    add_files("scene/*.cpp")
    add_defines("TINYGLTF_IMPLEMENTATION", "STB_IMAGE_IMPLEMENTATION", "STB_IMAGE_WRITE_IMPLEMENTATION")
    add_includedirs(".", {public = true})
    add_packages("glm", "tinygltf", {public = true})
    add_deps("etna")
target_end()

target("gui")
    set_kind("static")
    set_target_layout("common/gui")
    add_files("gui/ImGuiRenderer.cpp")
    add_includedirs(".", {public = true})
    add_deps("wsi", "etna")
    add_packages("imgui", {public = true})
target_end()

target("render_utils")
    set_kind("static")
    set_target_layout("common/render_utils")
    add_files("render_utils/QuadRenderer.cpp")
    add_includedirs(".", {public = true})
    add_includedirs("render_utils/shaders", {public = true})
    add_deps("etna")
    compile_shaders("shaders")
target_end()